dist: bionic

language: cpp

compiler:
  - gcc
  - clang

before_install:
  - sudo apt update
  - sudo apt -y install libssl-dev

before_script:
  - mkdir .build
  - cd .build
  - cmake -DCMAKE_BUILD_TYPE=Debug -DWITHOUT_TESTS=ON ..

script:
  - make
