language: cpp

compiler:
  - gcc
  - clang

before_install:
  - sudo apt update
  - sudo apt -y install libssl-dev=1.1\*

before_script:
  - mkdir .build
  - cd .build
  - cmake -DCMAKE_BUILD_TYPE=Debug ..

script:
  - make
  - ./alltests
