dist: bionic

language: cpp

compiler:
  - gcc
  - clang

before_install:
  - sudo apt update
  - sudo apt -y install libssl-dev wget
  - mkdir /tmp/build
  - cd /tmp/build
  - wget https://github.com/google/googletest/archive/release-1.10.0.tar.gz
  - tar -xf release-1.10.0.tar.gz
  - cd googletest-release-1.10.0
  - mkdir .build
  - cd .build
  - cmake ..
  - make
  - sudo make install
  - cd $TRAVIS_BUILD_DIR

before_script:
  - mkdir .build
  - cd .build
  - cmake -DCMAKE_BUILD_TYPE=Debug ..

script:
  - make
  - ./alltests
